# Generated by Django 5.1.6 on 2025-03-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=710)),
                ('rating', models.IntegerField(default=50)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(blank=True, default='', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('file', models.ImageField(upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dankbank_back.item')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('cuisine', models.CharField(blank=True, default='', max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='dankbank_back.item')),
            ],
        ),
        migrations.CreateModel(
            name='Dining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('gmap_url', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('price_range', models.CharField(blank=True, default='', max_length=200)),
                ('cuisine', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dining', to='dankbank_back.item')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, default='', max_length=200)),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dankbank_back.item')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('gmap_url', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='dankbank_back.item')),
            ],
        ),
    ]
